#!/usr/bin/env zsh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
# yabai -m config mouse_follows_focus          on
# yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   20

# Rules
yabai -m rule --add app="^Calendar$"           manage=off
yabai -m rule --add app="^Dictionary$"         manage=off
yabai -m rule --add app="^Disk Utility$"       manage=off
yabai -m rule --add app="^Simulator$"          manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^システム環境設定$"   manage=off
yabai -m rule --add app=".*AnyConnect.*"       manage=off

yabai -m config window_border off
# yabai -m config window_border_width 6
# yabai -m config window_border_placement inset
# yabai -m config active_window_border_color 0xff775759
# yabai -m config normal_window_border_color 0xff555555

yabai -m config window_opacity               off
# yabai -m config window_opacity_duration      0.0
# yabai -m config active_window_opacity        1.0
# yabai -m config normal_window_opacity        0.7

yabai -m config window_shadow                off
# yabai -m config insert_feedback_color        0xaad75f5f

# yabai -m window --toggle border
# yabai -m rule --add app=Terminal border=off

# restore position of floating windows when they are manually unfloated
# ~/dotfiles/yabai/yabai_restore.sh

# borders active_color="gradient(top_left=0x33B4FF30,bottom_right=0xF9B4FF30)" inactive_color=0xFF494d64 width=18.0 &
borders active_color=0xF9B4FF30 inactive_color=0xFF494d64 width=15.0 &

echo "yabai configuration loaded.."
